title: Srilekha Mandali
description: Data Engineer, ETL Developer, Data Analyst, and AI Automation professional specializing in enterprise data integration, analytics, and intelligent workflow solutions.

url: "https://srilekhamandali.github.io"
baseurl: "/portfolio"

author:
  name: Srilekha Mandali
  email: mandalisrilekha12@gmail.com

linkedin_url: "https://www.linkedin.com/in/srilekha-mandali-2849691ab"
github_url: "https://github.com/srilekhamandali"

show_downloads: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
